<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Our Products</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    </head>
    <body>
        <?php
            $products = (array) json_decode(
                file_get_contents("http://127.0.0.1:9001/products")
            );
        ?>
        
        <div class="container">
            <h1>Products</h1>

            <table class="table">
                <thead>
                    <tr>
                        <th>Product ID</th>
                        <th>Description</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        array_map(function ($item) {
                            $item = (array) $item;
                    ?>
                            <tr>
                                <td> <?= $item["id"] ?> </td>
                                <td> <?= $item["name"] ?> </td>
                                <td> <?= $item["price"] ?> </td>
                            </tr>
                    <?php 
                    }, $products);
                    ?>
                </tbody>
            </table>
        </div>
        
    </body>
</html>